import { Product } from './product';

export const PLANTS: Product[] = [
  {
    id: 0,
    latinName: 'Calathea Orbifolia',
    name: 'Isabella',
    price: 37.89,
    quantity: 1,
    image: 'foo',
  },
  {
    id: 1,
    latinName: 'Monstera Deliciosa',
    name: 'Alfredo',
    price: 28.69,
    quantity: 1,
    image: 'foo',
  },
  {
    id: 2,
    latinName: 'Areca',
    name: 'Marty',
    price: 31.29,
    quantity: 1,
    image: 'foo',
  },
  {
    id: 3,
    latinName: 'Ananas Mi Amigo',
    name: 'Anny',
    price: 19.99,
    quantity: 1,
    image: 'foo',
  },
  {
    id: 4,
    latinName: 'Kentaipalm',
    name: 'Howard',
    price: 36.69,
    quantity: 1,
    image: 'foo',
  },
  {
    id: 5,
    latinName: 'Cactus Euphorbia',
    name: 'Bob',
    price: 41.49,
    quantity: 1,
    image: 'foo',
  },
  {
    id: 6,
    latinName: 'Strelitizia Nicolai',
    name: 'Snico',
    price: 24.99,
    quantity: 1,
    image: 'foo',
  },
  {
    id: 7,
    latinName: 'Ficus Lyrata',
    name: 'Lies',
    price: 12.99,
    quantity: 1,
    image: 'foo',
  },
  {
    id: 8,
    latinName: 'Zamioculcas',
    name: 'Lucas',
    price: 30.99,
    quantity: 1,
    image: 'foo',
  },
];
